# Generated by Django 4.0.2 on 2022-04-02 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('presence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('type_user', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inttule', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.classe')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.classe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.utilisateur')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseMatiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.classe')),
                ('matiere_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='ClasseEnseignant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.classe')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='presence.utilisateur')),
            ],
        ),
    ]
